services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 20

  keycloak-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      POSTGRES_DB: ${KC_DB_NAME}
    volumes:
      - kcdbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KC_DB_USER} -d ${KC_DB_NAME} -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 20

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command:
      - start-dev
      - --import-realm
      - --http-enabled=true
      - --proxy-headers=xforwarded
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KC_DB_NAME}
      KEYCLOAK_ADMIN: ${KC_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
    volumes:
      - ./keycloak:/opt/keycloak/data/import:ro
      - ./keycloak-theme/adconnect:/opt/keycloak/themes/adconnect:ro
      

  backend:
    build: ./backend
    command: /bin/bash -lc "python manage_wait_for_db.py && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      CORS_ALLOWED_ORIGINS: http://localhost:5173
      OIDC_ISSUER: http://keycloak:8080/realms/demo
      OIDC_AUDIENCE: demo-spa
      OIDC_JWKS_URL: http://keycloak:8080/realms/demo/protocol/openid-connect/certs
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_REALM: demo
      KEYCLOAK_ADMIN_USER: ${KC_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      # Comma-separated domain allowlists (examples)
      SPONSOR_ALLOWED_DOMAINS: acme.com,corp.acme.com
      ADVERTISER_ALLOWED_DOMAINS: brand.com,ads.brand.com
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    environment:
      VITE_KEYCLOAK_URL: http://localhost:8080
      VITE_KEYCLOAK_REALM: demo
      VITE_KEYCLOAK_CLIENT_ID: demo-spa
      VITE_API_BASE: http://localhost:8000
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
      - keycloak

volumes:
  dbdata:
  kcdbdata:
